Fixed issues with packaging cassandra dependency libraries

diff --git a/docker/resources/systems/alpine-edge/Dockerfile b/docker/resources/systems/alpine-edge/Dockerfile
--- a/docker/resources/systems/alpine-edge/Dockerfile
+++ b/docker/resources/systems/alpine-edge/Dockerfile
@@ -6,7 +6,8 @@ RUN apk upgrade
 RUN apk update && apk add --no-cache \
     wget \
     git \
-    bash
+    bash \
+    zip
 
 # Use BASH shell for the rest of the Docker commands
 SHELL ["/bin/bash", "-c"]
@@ -18,6 +19,7 @@ RUN apk add --no-cache \
     libtool \
     cmake \
     openssl-dev \
+    gmp \
     gmp-dev \
     autoconf
 
@@ -26,17 +28,6 @@ RUN apk add --no-cache \
     php7 \
     php7-dev \
     php7-pear
-
-## Install autoconf (required for cassandra install)
-#RUN wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz \
-#&& tar xzf autoconf-2.69.tar.gz \
-#&& find . -maxdepth 1 -type f -name 'autoconf*.tar.gz' -delete \
-#&& { find . -maxdepth 1 -type d -name 'autoconf*'; echo 'autoconf'; } | xargs -n2 mv \
-#&& pushd autoconf \
-#&& ./configure \
-#&& make install \
-#&& popd \
-#|| { echo "Failed installing autoconf library." ; exit 1 ; }
 
 # Build libuv (Extract and delete tar, rename dir to 'libuv' and install)
 RUN wget http://dist.libuv.org/dist/v1.13.1/libuv-v1.13.1.tar.gz \
@@ -58,7 +49,7 @@ RUN git clone --recurse-submodules https://github.com/datastax/php-driver.git \
 || { echo "Failed cloning datastax Cassandra PHP driver git repository from GitHub." ; exit 3 ; }
 
 # Build C++ Cassandra (required because it's wrapped by PHP extension)
-# Also remove warnings as errors flag for cmake
+# Also remove warnings-as-errors flag for cmake
 WORKDIR /tmp/php-driver/lib/cpp-driver
 RUN find . -type f -iname '*.cmake' -exec sed -i "s/ -Werror//" {} \; \
 && cmake . \
@@ -74,11 +65,13 @@ RUN phpize
 RUN ./configure --with-cassandra=/tmp/php-driver/lib/cpp-driver --with-libdir=lib
 
 # Install Cassandra extension into PHP (these steps are not required but validate the installation of Cassandra)
-RUN pecl install /tmp/php-driver/ext/package.xml
-RUN echo 'extension=cassandra.so' >> $(php -i | awk '/^Loaded Configuration File/{print $NF}')
-RUN php -m | grep -Fxq "cassandra" || { echo "Cassandra module was not loaded by PHP. Installation failed." ; exit 5 ; }
+RUN pecl install /tmp/php-driver/ext/package.xml \
+&& echo 'extension=cassandra.so' >> $(php -i | awk '/^Loaded Configuration File/{print $NF}') \
+&& php -m | grep -Fxq "cassandra" \
+|| { echo "Cassandra module was not loaded by PHP. Installation failed." ; exit 5 ; }
 
 # Install zip/install scripts
 COPY /resources/systems/alpine-edge/resources/ /resources
 
+WORKDIR /resources
 CMD ["/bin/bash"]
